export interface EntityBase {
    // [PK] Stores unique identifier of the project type. Will be generated by system or a uuid.
    id?: string;
    // Create date time
    created?: string;
    // User or process name that created this record
    createdBy?: string;
    // User or process Id that created this record
    createdById?: string;
    // Update date time
    updated?: string;
    // User or process name that updated this record
    updatedBy?: string;
    // User or process Id that updated this record
    updatedById?: string;
}
